global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'Opportunities_microservice'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['172.16.1.1:32780']

  #- job_name: 'Opportunities_microservice_health'
  #  metrics_path: '/health'
  #  static_configs:
  #    - targets: ['172.16.1.1:32780']
  #  relabel_configs:
  #    - source_labels: [__metrics_path__]
  #      regex: /health
  #      target_label: __name__
  #      replacement: opportunities_microservice_health_status_1
  #    - source_labels: [opportunities_microservice_health_status_1]
  #      regex: '\b(Healthy|Unhealthy)\b'
  #      target_label: opportunities_microservice_health_status
  #      replacement: "$1"
  #      action: replace
  #    - source_labels: [opportunities_microservice_health_status]
  #      regex: '\s*(.*)\s*'
  #      target_label: opportunities_microservice_health_status
  #      replacement: '${1}'
  #      action: replace

  - job_name: 'Project_phases_microservice'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['172.16.1.1:32781']
  
  #- job_name: 'Project_phases_microservice_health'
  #  metrics_path: '/health'
  #  static_configs:
  #    - targets: ['172.16.1.1:32781']
  #  relabel_configs:
  #    - source_labels: [__metrics_path__]
  #      regex: /health
  #      target_label: __name__
  #      replacement: projects_phases_microservice_health_status_1
  #    - source_labels: [projects_phases_microservice_health_status_1]
  #      regex: '\b(Healthy|Unhealthy)\b'
  #      target_label: projects_phases_microservice_health_status
  #      replacement: "$1"
  #      action: replace
  #    - source_labels: [projects_phases_microservice_health_status]
  #      regex: '\s*(.*)\s*'
  #      target_label: projects_phases_microservice_health_status
  #      replacement: '${1}'
  #      action: replace


  - job_name: 'Projects_microservice'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['172.16.1.1:32782']

  #- job_name: 'Projects_microservice_health'
  #  metrics_path: '/health'
  #  static_configs:
  #    - targets: ['172.16.1.1:32782']
  #  relabel_configs:
  #    - source_labels: [__metrics_path__]
  #      regex: /health
  #      target_label: __name__
  #      replacement: projects_microservice_health_status_1
  #    - source_labels: [projects_microservice_health_status_1]
  #      regex: '\b(Healthy|Unhealthy)\b'
  #      target_label: projects_microservice_health_status
  #      replacement: "$1"
  #      action: replace
  #    - source_labels: [projects_microservice_health_status]
  #      regex: '\s*(.*)\s*'
  #      target_label: projects_microservice_health_status
  #      replacement: '${1}'
  #      action: replace

  - job_name: 'Risks_microservice'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['172.16.1.1:32783']

  #- job_name: 'Risks_microservice_health'
  #  metrics_path: '/health'
  #  static_configs:
  #    - targets: ['172.16.1.1:32783']
  #  relabel_configs:
  #    - source_labels: [__metrics_path__]
  #      regex: /health
  #      target_label: __name__
  #      replacement: risks_microservice_health_status_1
  #    - source_labels: [risks_microservice_health_status_1]
  #      regex: '\b(Healthy|Unhealthy)\b'
  #      target_label: risks_microservice_health_status
  #      replacement: "$1"
  #      action: replace
  #    - source_labels: [risks_microservice_health_status]
  #      regex: '\s*(.*)\s*'
  #      target_label: risks_microservice_health_status
  #      replacement: '${1}'
  #      action: replace

  - job_name: 'Risk_templates_microservice'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['172.16.1.1:32784']


  #- job_name: 'Risk_templates_microservice_health'
  #  metrics_path: '/health'
  #  static_configs:
  #    - targets: ['172.16.1.1:32784']
  #  relabel_configs:
  #    - source_labels: [__metrics_path__]
  #      regex: /health
  #      target_label: __name__
  #      replacement: risk_templates_microservice_health_status_1
  #    - source_labels: [risk_templates_microservice_health_status_1]
  #      regex: '\b(Healthy|Unhealthy)\b'
  #      target_label: risk_templates_microservice_health_status
  #      replacement: "$1"
  #      action: replace
  #    - source_labels: [risk_templates_microservice_health_status]
  #      regex: '\s*(.*)\s*'
  #      target_label: risk_templates_microservice_health_status
  #      replacement: '${1}'
  #      action: replace

  - job_name: 'Employees_microservice'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['172.16.1.1:32786']   
  
  #- job_name: 'Employees_microservice_health'
  #  metrics_path: '/health'
  #  static_configs:
  #    - targets: ['172.16.1.1:32786']
  #  relabel_configs:
  #    - source_labels: [__metrics_path__]
  #      regex: /health
  #      target_label: __name__
  #      replacement: employees_microservice_health_status_1
  #    - source_labels: [employees_microservice_health_status_1]
  #      regex: '\b(Healthy|Unhealthy)\b'
  #      target_label: employees_microservice_health_status
  #      replacement: "$1"
  #      action: replace
  #    - source_labels: [employees_microservice_health_status]
  #      regex: '\s*(.*)\s*'
  #      target_label: employees_microservice_health_status
  #      replacement: '${1}'
  #      action: replace
